#!/usr/bin/env bash
set -o errexit

# PRE-RUN SETUP & CONFIGURATION
########################################

MACHINE_ID_FILE="/etc/machine-id"

if [[ ! -f ${MACHINE_ID_FILE} ]]; then
    echo "ERROR: Unable to locate machine ID file at '${MACHINE_ID_FILE}'"
    exit 1
fi

# SCRIPT USAGE
########################################

function usage() {
	cat <<-EOF
	Usage: $(basename ${0}) [OPTION]...
	Get the machine's unique ID.

	OPTIONS:
	  -h, --help     Print this help dialogue
	  -r, --raw      Retuns the raw machine ID
	  -s, --short    Return a short (7 character) ID
	EOF
}

# OPTION / PARAMATER PARSING
########################################

PARSED_OPTIONS=$(getopt -n "${0}" -o hrs -l "help,raw,short" -- "$@")

eval set -- "${PARSED_OPTIONS}"

while true; do
    case "${1}" in
        -h|--help)  usage; exit ;;
        -r|--raw)   RAW=true; shift ;;
        -s|--short) SHORT=true; shift ;;
        --)         shift; break ;;
    esac
done

# SCRIPT FUNCTIONS
########################################

function rawMachineId() {
    echo "$(sed -e 's/^[[:space:]]//' ${MACHINE_ID_FILE})"
}

function hashedMachineId() {
    echo $(rawMachineId) | sha256sum | awk '{print $1}'
}

function main() {
    if [[ "${RAW}" == true ]]; then
        local MACHINE_ID="$(rawMachineId)"
    else
        local MACHINE_ID="$(hashedMachineId)"
    fi

    [[ "${SHORT}" == true ]] && echo ${MACHINE_ID:0:7} || echo ${MACHINE_ID}
}

# MAKE IT SO
########################################

main
